spring.application.name=EasyMart

# Configurações do servidor
server.port=8088

# Configurações do banco de dados H2 (banco de dados em memória para desenvolvimento)
spring.datasource.url=jdbc:h2:mem:easymartdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Configurações do JPA (Hibernate)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de logs
logging.level.org.springframework=INFO
logging.level.com.easymart=DEBUG

# Desabilitar spring.jpa.open-in-view
spring.jpa.open-in-view=false